server:
  port: 9998
gateway:
  route:
    config:
      data-id: gateway-router.json
      group: DEFAULT_GROUP
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        group: DEFAULT_GROUP
        heartBeatInterval: 3000
        heartBeatTimeout: 6000
        watchDelay: 12000
        ipDeleteTimeout: 12000
      username: nacos
      password: nacos
      server-addr: localhost:8848
  config:
    import:
      - optional:nacos:gateway.yaml
    gateway:
      discovery:
        locator:
          #自动为每个服务创建一个Router,，这个Router将以服务名开头的请求路径转发
          enabled: true
      httpclient:
        response-timeout: 3s
        connect-timeout: 3000
      globalcors:
        #跨域配置
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    sentinel:
      transport:
        dashboard: localhost:8080
      filter:
        enabled: false
      #sentinel控制台非懒加载
      eager: false
      datasource:
        #naocs存储的熔断规则
        degrade:
          nacos:
            server-addr: localhost:8848
            data-id: gateway-sentinel.json
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: degrade
        #nacos存储的流控规则
        gw-flow:
          nacos:
            server-addr: localhost:8848
            data-id: gw-flow.json
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: gw-flow

knife4j:
  gateway:
    enabled: true
    routes:
      - name: system
        service-name: system
        url: /sys/v2/api-docs
      - name: demo
        service-name: demo
        url: /demo/v2/api-docs

#  redis:
#    redisson:
#      config: |
#        clusterServersConfig:
#          idleConnectionTimeout: 10000
#          connectTimeout: 2000
#          timeout: 3000
#          retryAttempts: 3
#          retryInterval: 1500
#          password: cqt@1234
#          masterConnectionMinimumIdleSize: 24
#          masterConnectionPoolSize: 64
#          readMode: "MASTER"
#          subscriptionMode: "MASTER"
#          nodeAddresses:
#          - "redis://172.16.252.123:8001"
#          - "redis://172.16.252.124:8001"
#          - "redis://172.16.252.125:8001"
#          scanInterval: 1000
#          pingConnectionInterval: 30000
#          keepAlive: false
#          tcpNoDelay: true
#        threads: 16
#        nettyThreads: 32
#        codec: !<org.redisson.codec.MarshallingCodec> {}
#        transportMode: "NIO"
management:
  endpoints:
    web:
      exposure:
        include: '*'

